// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderTrackingApp.Models;

#nullable disable

namespace OrderTrackingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250415002420_AddCreatedByToODGController")]
    partial class AddCreatedByToODGController
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OrderTrackingApp.Models.CastConvocazioni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Attore")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Costume")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ODGOrderId")
                        .HasColumnType("int");

                    b.Property<string>("PickUp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pronti")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ODGOrderId");

                    b.ToTable("CastConvocazioni");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.CinemaOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AssProducer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DoP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DriveLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CinemaOrders");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Contatto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ODGOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ODGOrderId");

                    b.ToTable("Contatti");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CartellaFotoLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CinemaOrderId")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactFirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactLastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GoogleMapsLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CinemaOrderId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.ODGOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Catering")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CinemaOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Costumi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DayRec")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Film")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FineRiprese")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InformazioniUtili")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InizioRiprese")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Meteo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MezziTecnici")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoteProduzione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoteRegia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PausaPranzo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Produttore")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProntiAGirare")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Regista")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SFX_VFX")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SceneDaGirare")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SpecialEquipment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stunt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TermineLavorazione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TruccoeCapelli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CinemaOrderId");

                    b.ToTable("ODGOrders");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("longtext");

                    b.Property<string>("DriveLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Trasporti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Auto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Chi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dove")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ODGOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Ora")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ODGOrderId");

                    b.ToTable("Trasporti");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.TroupeOrari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ODGOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Orario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ODGOrderId");

                    b.ToTable("TroupeOrari");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHashManual")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("VisualName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderTrackingApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderTrackingApp.Models.CastConvocazioni", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.ODGOrder", "ODGOrder")
                        .WithMany("CastConvocazioni")
                        .HasForeignKey("ODGOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ODGOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Contatto", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.ODGOrder", "ODGOrder")
                        .WithMany("Contatti")
                        .HasForeignKey("ODGOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ODGOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Location", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.CinemaOrder", "CinemaOrder")
                        .WithMany("Locations")
                        .HasForeignKey("CinemaOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.ODGOrder", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.CinemaOrder", "CinemaOrder")
                        .WithMany("ODGs")
                        .HasForeignKey("CinemaOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Trasporti", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.ODGOrder", "ODGOrder")
                        .WithMany("Trasporti")
                        .HasForeignKey("ODGOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ODGOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.TroupeOrari", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.ODGOrder", "ODGOrder")
                        .WithMany("TroupeOrari")
                        .HasForeignKey("ODGOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ODGOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.CinemaOrder", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("ODGs");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.ODGOrder", b =>
                {
                    b.Navigation("CastConvocazioni");

                    b.Navigation("Contatti");

                    b.Navigation("Trasporti");

                    b.Navigation("TroupeOrari");
                });
#pragma warning restore 612, 618
        }
    }
}
