// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderTrackingApp.Models;

#nullable disable

namespace OrderTrackingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OrderTrackingApp.Models.AppInstallation", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabasePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationProfile")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LockedBySessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousState")
                        .HasColumnType("TEXT");

                    b.HasKey("InstallationId");

                    b.ToTable("AppInstallations");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.AttoreRipresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiornoRipresaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeAttore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GiornoRipresaId");

                    b.ToTable("AttoriRipresa");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.CastConvocazioni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Costume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ODGOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PickUp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pronti")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trucco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ODGOrderId");

                    b.ToTable("CastConvocazioni");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fotografia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Audio"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Luci"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Grip"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Extra"
                        });
                });

            modelBuilder.Entity("OrderTrackingApp.Models.CentroCosto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CinemaOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CinemaOrderId");

                    b.ToTable("CentriCosto");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.CinemaOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssProducer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CinemaOrders");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Contatto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ODGOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ODGOrderId");

                    b.ToTable("Contatti");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.DamageReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("RentalRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RentalRequestId");

                    b.ToTable("DamageReport");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.EmergencyContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Relation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TroupeCastContactId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TroupeCastContactId")
                        .IsUnique();

                    b.ToTable("EmergencyContacts");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.GiornoRipresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroGiorno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Osservazioni")
                        .HasColumnType("TEXT");

                    b.Property<int>("PianoDiLavorazioneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PianoDiLavorazioneId");

                    b.ToTable("GiorniRipresa");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CartellaFotoLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CinemaOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleMapsLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CinemaOrderId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.LocationRipresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiornoRipresaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GiornoRipresaId");

                    b.ToTable("LocationsRipresa");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.ODGOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Catering")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CinemaOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Costumi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DayRec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Film")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FineRiprese")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InformazioniUtili")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InizioRiprese")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Meteo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MezziTecnici")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteProduzione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteRegia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PausaPranzo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Produttore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProntiAGirare")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regista")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SFX_VFX")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneDaGirare")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialEquipment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stunt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TermineLavorazione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TruccoeCapelli")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CinemaOrderId");

                    b.ToTable("ODGOrders");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Permessi");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.PianoDiLavorazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CinemaOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduzione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Produttore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regista")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitoloCortometraggio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CinemaOrderId");

                    b.ToTable("PianiDiLavorazione");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.ProjectPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectPermissions");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.RentalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("RentalItems");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.RentalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminModificationNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<int>("CinemaOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEditableByUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptPdfPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserVisualName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CinemaOrderId");

                    b.ToTable("RentalRequests");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.RentalRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RentalItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RentalRequestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RentalItemId");

                    b.HasIndex("RentalRequestId");

                    b.ToTable("RentalRequestItems");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.ScenaRipresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<int>("GiornoRipresaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroScena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GiornoRipresaId");

                    b.ToTable("SceneRipresa");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Trasporti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Chi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dove")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ODGOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ora")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ODGOrderId");

                    b.ToTable("Trasporti");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.TroupeCastContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CinemaOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAccidentInsurance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("License")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subscription")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CinemaOrderId");

                    b.ToTable("TroupeCastContacts");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.TroupeOrari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ODGOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Orario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ODGOrderId");

                    b.ToTable("TroupeOrari");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHashManual")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("VisualName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OrderTrackingApp.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("PermessiUtente");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.VoceSpesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentroCostoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScontrinoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CentroCostoId");

                    b.ToTable("VociSpesa");
                });

            modelBuilder.Entity("ProjectFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectFiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderTrackingApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderTrackingApp.Models.AttoreRipresa", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.GiornoRipresa", "GiornoRipresa")
                        .WithMany("Attori")
                        .HasForeignKey("GiornoRipresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiornoRipresa");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.CastConvocazioni", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.ODGOrder", "ODGOrder")
                        .WithMany("CastConvocazioni")
                        .HasForeignKey("ODGOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ODGOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.CentroCosto", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.CinemaOrder", "CinemaOrder")
                        .WithMany("CentriCosto")
                        .HasForeignKey("CinemaOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Contatto", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.ODGOrder", "ODGOrder")
                        .WithMany("Contatti")
                        .HasForeignKey("ODGOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ODGOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.DamageReport", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.RentalRequest", "RentalRequest")
                        .WithMany()
                        .HasForeignKey("RentalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalRequest");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.EmergencyContact", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.TroupeCastContact", "TroupeCastContact")
                        .WithOne("EmergencyContact")
                        .HasForeignKey("OrderTrackingApp.Models.EmergencyContact", "TroupeCastContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TroupeCastContact");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.GiornoRipresa", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.PianoDiLavorazione", "PianoDiLavorazione")
                        .WithMany("GiorniRipresa")
                        .HasForeignKey("PianoDiLavorazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PianoDiLavorazione");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Location", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.CinemaOrder", "CinemaOrder")
                        .WithMany("Locations")
                        .HasForeignKey("CinemaOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.LocationRipresa", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.GiornoRipresa", "GiornoRipresa")
                        .WithMany("Locations")
                        .HasForeignKey("GiornoRipresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiornoRipresa");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.ODGOrder", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.CinemaOrder", "CinemaOrder")
                        .WithMany("ODGs")
                        .HasForeignKey("CinemaOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.PianoDiLavorazione", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.CinemaOrder", "CinemaOrder")
                        .WithMany("PianiDiLavorazione")
                        .HasForeignKey("CinemaOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.RentalItem", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.RentalRequest", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.CinemaOrder", "CinemaOrder")
                        .WithMany("RentalRequests")
                        .HasForeignKey("CinemaOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CinemaOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.RentalRequestItem", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.RentalItem", "RentalItem")
                        .WithMany()
                        .HasForeignKey("RentalItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderTrackingApp.Models.RentalRequest", "RentalRequest")
                        .WithMany("RequestItems")
                        .HasForeignKey("RentalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalItem");

                    b.Navigation("RentalRequest");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.ScenaRipresa", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.GiornoRipresa", "GiornoRipresa")
                        .WithMany("Scene")
                        .HasForeignKey("GiornoRipresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiornoRipresa");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Trasporti", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.ODGOrder", "ODGOrder")
                        .WithMany("Trasporti")
                        .HasForeignKey("ODGOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ODGOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.TroupeCastContact", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.CinemaOrder", "CinemaOrder")
                        .WithMany()
                        .HasForeignKey("CinemaOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.TroupeOrari", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.ODGOrder", "ODGOrder")
                        .WithMany("TroupeOrari")
                        .HasForeignKey("ODGOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ODGOrder");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.UserPermission", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderTrackingApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.VoceSpesa", b =>
                {
                    b.HasOne("OrderTrackingApp.Models.CentroCosto", "CentroCosto")
                        .WithMany("Spese")
                        .HasForeignKey("CentroCostoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroCosto");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.CentroCosto", b =>
                {
                    b.Navigation("Spese");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.CinemaOrder", b =>
                {
                    b.Navigation("CentriCosto");

                    b.Navigation("Locations");

                    b.Navigation("ODGs");

                    b.Navigation("PianiDiLavorazione");

                    b.Navigation("RentalRequests");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.GiornoRipresa", b =>
                {
                    b.Navigation("Attori");

                    b.Navigation("Locations");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.ODGOrder", b =>
                {
                    b.Navigation("CastConvocazioni");

                    b.Navigation("Contatti");

                    b.Navigation("Trasporti");

                    b.Navigation("TroupeOrari");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.PianoDiLavorazione", b =>
                {
                    b.Navigation("GiorniRipresa");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.RentalRequest", b =>
                {
                    b.Navigation("RequestItems");
                });

            modelBuilder.Entity("OrderTrackingApp.Models.TroupeCastContact", b =>
                {
                    b.Navigation("EmergencyContact");
                });
#pragma warning restore 612, 618
        }
    }
}
